const districtsSchools = {
    "Alum Rock Union Elementary": [
        "Adelante Dual Language Academy",
        "Adelante Dual Language Academy II",
        "Alpha: Blanca Alvarado",
        "Aptitud Community Academy at Goss",
        "Ben Painter Elementary",
        "KIPP Heartwood Academy",
        "Kipp Prize Preparatory Academy",
        "Learning in an Urban Community with High Achievement (L.U.C.H.A.)",
        "Linda Vista Elementary",
        "Lyndale Elementary",
        "Millard McCollam Elementary",
        "O. S. Hubbard Elementary",
        "Ocala Middle",
        "Renaissance at Mathson",
        "Russo/McEntee Academy",
        "San Antonio Elementary",
        "Thomas P. Ryan Elementary",
        "William Sheppard Middle"
    ],
    "Berryessa Union Elementary": [
        "Berryessa Union Elementary",
        "Brooktree Elementary",
        "Majestic Way Elementary",
        "Morrill Middle",
        "Noble Elementary",
        "Northwood Elementary",
        "Piedmont Middle",
        "Ruskin Elementary",
        "Sierramont Middle",
        "Summerdale Elementary",
        "Vinci Park Elementary"
    ],
    "Cambrian": [
        "Bagby Elementary",
        "Fammatre Elementary",
        "Farnham Charter",
        "Price Charter Middle",
        "Sartorette Charter",
        "Steindorf STEAM K-8 Magnet"
    ],
    "Campbell Union": [
        "Blackford Elementary",
        "Campbell School of Innovation",
        "Capri Elementary",
        "Castlemont Elementary",
        "Forest Hill Elementary",
        "Lynhaven Elementary",
        "Marshall Lane Elementary",
        "Monroe Middle",
        "Rolling Hills Middle",
        "Rosemary",
        "Sherman Oaks Elementary",
        "Village"
    ],
    "Campbell Union High": [
        "Boynton High",
        "Branham High",
        "Campbell Adult and Community Education",
        "Del Mar High",
        "Leigh High",
        "Prospect High",
        "Westmont High"
    ],
    "Cupertino Union": [
        "Abraham Lincoln Elementary",
        "Blue Hills Elementary",
        "C. B. Eaton Elementary",
        "Chester W. Nimitz Elementary",
        "Christa McAuliffe",
        "Cupertino Middle",
        "D. J. Sedgwick Elementary",
        "Dwight D. Eisenhower Elementary",
        "Garden Gate Elementary",
        "Joaquin Miller Middle",
        "John F. Kennedy Middle",
        "John Muir Elementary",
        "L. P. Collins Elementary",
        "Louis E. Stocklmeir Elementary",
        "Manuel De Vargas Elementary",
        "Montclaire Elementary",
        "Murdock-Portal Elementary",
        "Nelson S. Dilworth Elementary",
        "Sam H. Lawson Middle",
        "Stevens Creek Elementary",
        "Warren E. Hyde Middle",
        "West Valley Elementary",
        "William Faria Elementary"
    ],
    "East Side Union High": [
        "ACE Charter High",
        "Adult Education Eastside Union",
        "Adult Education Program",
        "Alpha Cindy Avitia High",
        "Andrew P. Hill High",
        "Apollo High",
        "B. Roberto Cruz Leadership Academy",
        "Calero High",
        "Escuela Popular Accelerated Family Learning",
        "Escuela Popular/Center for Training and Careers, Family Learning",
        "Evergreen Valley High",
        "Foothill High",
        "Independence High",
        "James Lick High",
        "KIPP San Jose Collegiate",
        "Latino College Preparatory Academy",
        "Luis Valdez Leadership Academy",
        "Mt. Pleasant High",
        "Oak Grove High",
        "Overfelt Adult",
        "Pegasus High",
        "Phoenix High",
        "Piedmont Hills High",
        "San Jose Conservation Corps Charter",
        "Santa Teresa High",
        "Silver Creek High",
        "William C. Overfelt High",
        "Yerba Buena High"
    ],
    "Evergreen Elementary": [
        "Cadwallader Elementary",
        "Carolyn A. Clark Elementary",
        "Cedar Grove Elementary",
        "Chaboya Middle",
        "Evergreen Elementary",
        "George V. LeyVa Intermediate",
        "Holly Oak Elementary",
        "James Franklin Smith Elementary",
        "John J. Montgomery Elementary",
        "Katherine R. Smith Elementary",
        "Millbrook Elementary",
        "Norwood Creek Elementary",
        "O. B. Whaley Elementary",
        "Quimby Oak Middle",
        "Silver Oak Elementary",
        "Tom Matsumoto Elementary"
    ],
    "Franklin-McKinley Elementary": [
        "ACE Esperanza Middle",
        "Bridges Academy",
        "Captain Jason M. Dahl Elementary",
        "College Connection Academy",
        "Franklin Elementary",
        "G. W. Hellyer Elementary",
        "Jeanne R. Meadows Elementary",
        "KIPP Heritage Academy",
        "Lairon College Preparatory Academy",
        "Robert F. Kennedy Elementary",
        "Rocketship Mosaic Elementary",
        "Rocketship Spark Academy",
        "Santee Elementary",
        "Shirakawa (George, Sr.) Elementary",
        "Stonegate Elementary",
        "Sylvandale Middle",
        "Voices College-Bound Language Academy",
        "Windmill Springs Elementary"
    ],
    "Fremont Union High": [
        "Community Day",
        "Cupertino High",
        "FUHSD Adult",
        "Fremont High",
        "Homestead High",
        "Lynbrook High",
        "Monta Vista High"
    ],
    "Gilroy Unified": [
        "Brownell Middle",
        "Christopher High",
        "Dr. TJ Owens Gilroy Early College Academy",
        "El Roble Elementary",
        "Eliot Elementary",
        "Gilroy Adult Education",
        "Gilroy High",
        "Gilroy Prep (a Navigator School)",
        "Gilroy Special Ed Preschool",
        "Glen View Elementary",
        "Las Animas Elementary",
        "Luigi Aprea Elementary",
        "Mt. Madonna High",
        "Rod Kelley Elementary",
        "Rucker Elementary",
        "Solorsano Middle",
        "South Valley Middle"
    ],
    "Lakeside Joint": [
        "Lakeside Elementary"
    ],
    "Loma Prieta Joint Union Elementary": [
        "C. T. English Middle",
        "Loma Prieta Elementary"
    ],
    "Los Altos Elementary": [
        "Almond Elementary",
        "Ardis G. Egan Junior High",
        "Covington Elementary",
        "Gardner Bullis Elementary",
        "Georgina P. Blach Junior High",
        "LASD Preschool",
        "Loyola Elementary",
        "Oak Avenue Elementary",
        "Santa Rita Elementary",
        "Springer Elementary"
    ],
    "Los Gatos Union Elementary": [
        "Blossom Hill Elementary",
        "Daves Avenue Elementary",
        "Lexington Elementary",
        "Louise Van Meter Elementary",
        "Raymond J. Fisher Middle"
    ],
    "Los Gatos-Saratoga Union High": [
        "Los Gatos High",
        "Saratoga High"
    ],
    "Luther Burbank": [
        "Luther Burbank Elementary"
    ],
    "Metro Education": [
        "Silicon Valley Career Technical Education"
    ],
    "Milpitas Unified": [
        "Alexander Rose Elementary",
        "Anthony Spangler Elementary",
        "Calaveras Hills",
        "Curtner Elementary",
        "John Sinnott Elementary",
        "Joseph Weller Elementary",
        "Mabel Mattos Elementary",
        "Marshall Pomeroy Elementary",
        "Milpitas Adult",
        "Milpitas High",
        "Milpitas Middle College High",
        "Pearl Zanker Elementary",
        "Rancho Milpitas Middle",
        "Robert Randall World Languages",
        "Thomas Russell Middle",
        "William Burnett Elementary"
    ],
    "Moreland": [
        "Country Lane Elementary",
        "Easterbrook Discovery",
        "George C. Payne Elementary",
        "Gussie M. Baker Elementary",
        "Latimer",
        "Leroy Anderson Elementary",
        "Moreland Middle"
    ],
    "Morgan Hill Unified": [
        "Ann Sobrato High",
        "Barrett Elementary",
        "Central High (Continuation)",
        "Charter School of Morgan Hill",
        "El Toro Health Science Academy",
        "Jackson Academy of Music and Math (JAMM)",
        "Lewis H. Britton Middle",
        "Live Oak High",
        "Los Paseos Elementary",
        "Martin Murphy Middle",
        "Morgan Hill Community Adult",
        "Nordstrom Elementary",
        "P. A. Walsh STEAM Academy",
        "Paradise Valley Engineering Academy",
        "San Martin Gwinn Environmental Science Academy"
    ],
    "Mount Pleasant Elementary": [
        "August Boeger Middle",
        "Ida Jew Academies",
        "Mt. Pleasant Elementary",
        "Robert Sanders Elementary",
        "Valle Vista Elementary"
    ],
    "Mountain View Whisman": [
        "Amy Imai Elementary",
        "BMO Preschool at Latham",
        "Benjamin Bubb Elementary",
        "Crittenden Middle",
        "Edith Landels Elementary",
        "Gabriela Mistral Elementary",
        "Isaac Newton Graham Middle",
        "Jose Antonio Vargas Elementary",
        "Mariano Castro Elementary",
        "Monta Loma Elementary",
        "Stevenson Elementary",
        "Theuerkauf Elementary"
    ],
    "Mountain View-Los Altos Union High": [
        "Adult Education",
        "Alta Vista High",
        "Los Altos High",
        "Mountain View High"
    ],
    "Oak Grove Elementary": [
        "Anderson (Alex) Elementary",
        "Baldwin (Julia) Elementary",
        "Bernal Intermediate",
        "Christopher Elementary",
        "Davis (Caroline) Intermediate",
        "Del Roble Elementary",
        "Edenvale Elementary",
        "Frost (Earl) Elementary",
        "Hayes Elementary",
        "Herman (Leonard) Intermediate",
        "Indigo",
        "Ledesma (Rita) Elementary",
        "Oak Ridge Elementary",
        "Parkview Elementary",
        "Sakamoto Elementary",
        "Santa Teresa Elementary",
        "Stipe (Samuel) Elementary",
        "Taylor (Bertha) Elementary"
    ],
    "Orchard Elementary": [
        "Orchard Elementary"
    ],
    "Palo Alto Unified": [
        "Addison Elementary",
        "Barron Park Elementary",
        "Duveneck Elementary",
        "El Carmelo Elementary",
        "Ellen Fletcher Middle",
        "Escondido Elementary",
        "Fairmeadow Elementary",
        "Frank S. Greene Jr. Middle",
        "Greendell",
        "Henry M. Gunn High",
        "Herbert Hoover Elementary",
        "Jane Lathrop Stanford Middle",
        "Juana Briones Elementary",
        "Lucille M. Nixon Elementary",
        "Ohlone Elementary",
        "Packard Children's Hospital/Stanford",
        "Palo Alto Adult Education",
        "Palo Alto High",
        "Palo Alto Middle College High",
        "Palo Verde Elementary",
        "Walter Hays Elementary"
    ],
    "SBE - KIPP Navigate College Prep": [
        "KIPP Navigate College Prep"
    ],
    "San Jose Unified": [
        "ACE Inspire Academy",
        "Abraham Lincoln High",
        "Allen at Steinbeck",
        "Almaden Elementary",
        "Anne Darling Elementary",
        "Booksin Elementary",
        "Bret Harte Middle",
        "Broadway High",
        "Canoas Elementary",
        "Castillero Middle",
        "Empire Gardens Elementary",
        "Ernesto Galarza Elementary",
        "Gardner Elementary",
        "Grant Elementary",
        "Graystone Elementary",
        "Gunderson High",
        "Hacienda Science/Environmental Magnet",
        "Hammer Montessori at Galarza Elementary",
        "Herbert Hoover Middle",
        "Horace Mann Elementary",
        "John Muir Middle",
        "Leland High",
        "Liberty Alternative",
        "Los Alamitos Elementary",
        "Lowell Elementary",
        "Merritt Trace Elementary",
        "Muwekma Ohlone Middle",
        "Pioneer High",
        "Rachel Carson Elementary",
        "Reed Elementary",
        "River Glen",
        "San Jose High",
        "Schallenberger Elementary",
        "Selma Olinder Elementary",
        "Silicon Valley Adult Education Program",
        "Simonds Elementary",
        "Terrell Elementary",
        "Walter L. Bachrodt Elementary",
        "Washington Elementary",
        "Williams Elementary",
        "Willow Glen Elementary",
        "Willow Glen High",
        "Willow Glen Middle"
    ],
    "Santa Clara County Office of Education": [
        "ACE Empower Academy",
        "Alpha: Cornerstone Academy Preparatory",
        "Alpha: Jose Hernandez",
        "Bullis Charter",
        "Discovery Charter",
        "Discovery Charter II",
        "Opportunity Youth Academy",
        "Rocketship Academy Brilliant Minds",
        "Rocketship Alma Academy",
        "Rocketship Discovery Prep",
        "Rocketship Fuerza Community Prep",
        "Rocketship Los Suenos Academy",
        "Rocketship Mateo Sheedy Elementary",
        "Rocketship Rising Stars",
        "Rocketship Si Se Puede Academy",
        "Santa Clara County Community",
        "Santa Clara County Court",
        "Santa Clara County Special Education",
        "Summit Public School: Tahoma",
        "Sunrise Middle",
        "University Preparatory Academy Charter",
        "Voices College-Bound Language Academy at Morgan Hill",
        "Voices College-Bound Language Academy at Mt. Pleasant"
    ],
    "Santa Clara County ROP": [
        "Santa Clara County ROP-South"
    ],
    "Santa Clara Unified": [
        "Abram Agnew Elementary",
        "Adrian Wilcox High",
        "Bowers Elementary",
        "Bracher Elementary",
        "Braly Elementary",
        "Briarwood Elementary",
        "Buchser Middle",
        "C. W. Haman Elementary",
        "Central Park Elementary",
        "Dolores Huerta Middle",
        "Don Callejon",
        "George Mayne Elementary",
        "Juan Cabrillo Middle",
        "Kathleen MacDonald High",
        "Kathryn Hughes Elementary",
        "Laurelwood Elementary",
        "Marian A. Peterson Middle",
        "Millikin Elementary",
        "Mission Early College High",
        "Montague Elementary",
        "New Valley Continuation High",
        "Pomeroy Elementary",
        "Ponderosa Elementary",
        "Santa Clara Adult",
        "Santa Clara Community Day",
        "Santa Clara High",
        "Scott Lane Elementary",
        "Sutter Elementary",
        "Washington Open Elementary",
        "Westwood Elementary",
        "Wilson Alternative"
    ],
    "Saratoga Union Elementary": [
        "Argonaut Elementary",
        "Foothill Elementary",
        "Redwood Middle",
        "Saratoga Elementary",
        "Saratoga Special Services Preschool"
    ],
    "Sunnyvale": [
        "Bishop Elementary",
        "Cherry Chase Elementary",
        "Columbia Middle",
        "Cumberland Elementary",
        "Ellis Elementary",
        "Fairwood Elementary",
        "Lakewood Elementary",
        "San Miguel Elementary",
        "Sunnyvale Middle",
        "Vargas Elementary"
    ],
    "Union Elementary": [
        "Alta Vista Elementary",
        "Carlton Elementary",
        "Dartmouth Middle",
        "Guadalupe Elementary",
        "Lietz Elementary",
        "Noddin Elementary",
        "Oster Elementary",
        "Union Middle"
    ]
};